// Generator: src/tokens.ts (hex/rgba source of truth) -> src/tokens.css (OKLCH).
// Run via `bun run gen:tokens`. The output is committed + Biome-excluded; a CI
// drift gate regenerates and fails on a dirty diff, so tokens.css always matches
// tokens.ts. OKLCH is the shadcn v4 canon (P3-gamut, homogeneous with `shadcn add`);
// keeping hex at the source keeps the design palette drift-free.

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { colorTokens, type ThemeToken } from '../src/tokens.ts'

type Rgba = { r: number; g: number; b: number; a: number }

/** Parse `#rgb` / `#rrggbb` / `rgb(...)` / `rgba(...)` into linearizable [0,1] channels. */
function parseColor(input: string): Rgba {
  const s = input.trim()
  if (s.startsWith('#')) {
    const hex = s.slice(1)
    const step = hex.length === 3 ? 1 : 2
    const at = (i: number) => {
      const part = hex.slice(i * step, i * step + step)
      return Number.parseInt(step === 1 ? part + part : part, 16) / 255
    }
    return { r: at(0), g: at(1), b: at(2), a: 1 }
  }
  const nums = s
    .slice(s.indexOf('(') + 1, s.indexOf(')'))
    .split(',')
    .map((n) => Number(n.trim()))
  return { r: nums[0] / 255, g: nums[1] / 255, b: nums[2] / 255, a: nums[3] ?? 1 }
}

const srgbToLinear = (c: number) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)
const linearToSrgb = (c: number) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055)

/** Linear sRGB -> OKLCH (L, C, h°). */
function rgbToOklch({ r, g, b }: Rgba) {
  const lr = srgbToLinear(r)
  const lg = srgbToLinear(g)
  const lb = srgbToLinear(b)
  const l = Math.cbrt(0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb)
  const m = Math.cbrt(0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb)
  const s = Math.cbrt(0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb)
  const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s
  const a = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s
  const bb = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s
  const C = Math.hypot(a, bb)
  let h = (Math.atan2(bb, a) * 180) / Math.PI
  if (h < 0) h += 360
  return { L, C, h }
}

/** OKLCH -> sRGB [0,255], for the round-trip self-check. */
function oklchToRgb255({ L, C, h }: { L: number; C: number; h: number }) {
  const a = C * Math.cos((h * Math.PI) / 180)
  const b = C * Math.sin((h * Math.PI) / 180)
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3
  const lr = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
  const lg = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
  const lb = -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s
  const to255 = (c: number) => Math.round(Math.min(1, Math.max(0, linearToSrgb(c))) * 255)
  return { r: to255(lr), g: to255(lg), b: to255(lb) }
}

/** Deterministic fixed-precision, trailing zeros stripped. */
const round = (n: number, p: number) => Number(n.toFixed(p))

function toOklchString(value: string): string {
  const rgba = parseColor(value)
  const { L, C, h } = rgbToOklch(rgba)
  const near = C < 1e-4
  const l = round(L, 5)
  const c = near ? 0 : round(C, 5)
  const hue = near ? 0 : round(h, 3)
  const alpha = rgba.a < 1 ? ` / ${round(rgba.a, 4)}` : ''

  // Round-trip guard: the emitted OKLCH must reproduce the source sRGB byte-exactly
  // (the precision above is tuned so every token in tokens.ts round-trips with zero
  // drift) — so the palette stays bit-identical to the hex design source, and a
  // precision/matrix regression fails the build instead of shifting a colour.
  const back = oklchToRgb255({ L: l, C: c, h: hue })
  const drift = Math.max(
    Math.abs(back.r - Math.round(rgba.r * 255)),
    Math.abs(back.g - Math.round(rgba.g * 255)),
    Math.abs(back.b - Math.round(rgba.b * 255)),
  )
  if (drift > 0) {
    throw new Error(`gen-tokens: ${value} -> oklch(${l} ${c} ${hue}) drifts ${drift}/255`)
  }
  return `oklch(${l} ${c} ${hue}${alpha})`
}

const block = (selector: string, side: 'light' | 'dark', tokens: readonly ThemeToken[]) =>
  `${selector} {\n${tokens.map((t) => `  --${t.name}: ${toOklchString(t[side])};`).join('\n')}\n}`

const themeMap = `@theme inline {\n${colorTokens
  .map((t) => `  --color-${t.name}: var(--${t.name});`)
  .join('\n')}\n}`

const css = `/* GENERATED by scripts/gen-tokens.ts from src/tokens.ts — DO NOT EDIT.
   Edit src/tokens.ts then run \`bun run gen:tokens\`. */

${block(':root', 'light', colorTokens)}

${block('.dark', 'dark', colorTokens)}

${themeMap}
`

const out = fileURLToPath(new URL('../src/tokens.css', import.meta.url))
writeFileSync(out, css)
console.log(`gen-tokens: wrote ${colorTokens.length} tokens -> ${out}`)
