#!/usr/bin/env bun
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import StyleDictionary from 'style-dictionary'

// Build the DTCG token source (tokens/**/*.json) into two artifacts:
//   - src/tokens.css     — CSS custom properties (the "→ CSS vars" deliverable)
//   - src/tokens.gen.ts  — the nested, typed token map the JS contract re-exports
// Both are generated + committed (like schema.gen.ts) and Biome-excluded. Run
// `bun run build` after editing tokens/.
const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..')

// Custom format: rebuild the nested token tree (by each token's `path`) so the
// TS contract keeps its ergonomic `semantic.bg.canvas` shape from one source.
StyleDictionary.registerFormat({
  name: 'ts/nested',
  format: async ({ dictionary }) => {
    const root: Record<string, unknown> = {}
    for (const token of dictionary.allTokens) {
      const path = token.path
      let node = root
      for (const key of path.slice(0, -1)) {
        node[key] ??= {}
        node = node[key] as Record<string, unknown>
      }
      // DTCG keeps the resolved value under `$value`; older tokens use `.value`.
      node[path[path.length - 1] as string] = token.$value ?? token.value
    }
    return (
      '// GENERATED by `bun run build` (style-dictionary) from tokens/**/*.json — DO NOT EDIT.\n\n' +
      `export const tokens = ${JSON.stringify(root, null, 2)} as const\n`
    )
  },
})

const sd = new StyleDictionary({
  source: [join(pkgRoot, 'tokens/**/*.json')],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: `${pkgRoot}/src/`,
      files: [{ destination: 'tokens.css', format: 'css/variables' }],
    },
    ts: {
      transformGroup: 'js',
      buildPath: `${pkgRoot}/src/`,
      files: [{ destination: 'tokens.gen.ts', format: 'ts/nested' }],
    },
  },
})

await sd.buildAllPlatforms()
console.error('fe-tokens: built src/tokens.css + src/tokens.gen.ts')
