// GENERATED by `bun run build` (style-dictionary) from tokens/**/*.json — DO NOT EDIT.

export const tokens = {
  "color": {
    "brand": {
      "500": "#6d28d9",
      "600": "#5b21b6",
      "700": "#4c1d95"
    },
    "gray": {
      "50": "#f9fafb",
      "200": "#e5e7eb",
      "500": "#6b7280",
      "800": "#1f2937",
      "900": "#111827"
    },
    "white": "#ffffff"
  },
  "space": {
    "xs": "0.25rem",
    "sm": "0.5rem",
    "md": "1rem",
    "lg": "1.5rem",
    "xl": "2rem"
  },
  "radius": {
    "sm": "0.25rem",
    "md": "0.5rem",
    "lg": "0.75rem"
  },
  "bg": {
    "canvas": "#f9fafb",
    "surface": "#ffffff"
  },
  "fg": {
    "default": "#111827",
    "muted": "#6b7280"
  },
  "border": {
    "subtle": "#e5e7eb"
  },
  "accent": {
    "default": "#5b21b6",
    "emphasis": "#4c1d95"
  }
} as const
