// GENERATED by `bun run gen:api` from the backend OpenAPI document — DO NOT EDIT.
// Regenerate after any backend contract change; CI fails the drift gate on a dirty diff.

export interface paths {
    "/api/words/{language}/{word}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["words.getWord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/words/{language}/{word}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["words.getWordState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/words/{language}/{word}/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["words.buildWord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/words/{language}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["words.search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/words/{language}/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["words.counts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WordNotReadyError: {
            /** @enum {string} */
            _tag: "WordNotReadyError";
        };
        WordAlreadyReadyError: {
            /** @enum {string} */
            _tag: "WordAlreadyReadyError";
        };
        WordBuildInProgressError: {
            /** @enum {string} */
            _tag: "WordBuildInProgressError";
        };
        InvalidWordInputError: {
            /** @enum {string} */
            _tag: "InvalidWordInputError";
            input: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "words.getWord": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                word: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string & unknown;
                        word: string & unknown;
                        /** @enum {string} */
                        language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                        /** @enum {string} */
                        status: "pending" | "running" | "succeeded" | "failed";
                        coreDefinition: string;
                        lexical: {
                            partOfSpeech: string;
                            countable?: boolean;
                            plural?: {
                                primary: string;
                                also: string[];
                            };
                            register: string[];
                        };
                        pronunciation: {
                            ipa: string;
                            respelling: string;
                            audio: {
                                uk: string | null;
                                us: string | null;
                            };
                        };
                        tiers: {
                            quick: {
                                title: string;
                                body: string;
                                examples: {
                                    text: string;
                                    register: string;
                                }[];
                            };
                            everyday: {
                                title: string;
                                body: string;
                                examples: {
                                    text: string;
                                    register: string;
                                }[];
                            };
                            deep: {
                                title: string;
                                body: string;
                                examples: {
                                    text: string;
                                    register: string;
                                }[];
                            };
                            cultural: {
                                title: string;
                                body: string;
                                examples: {
                                    text: string;
                                    register: string;
                                }[];
                            };
                        };
                        etymology: {
                            summary: string;
                            firstAttested: {
                                year: ((number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN")) | null;
                                language: string;
                            };
                            origin: {
                                from: string;
                                to: string;
                                gloss: string;
                            };
                            descent: {
                                when: string;
                                form: string;
                                languageName: string;
                                gloss: string;
                                citation?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                            }[];
                        };
                        authorExamples: {
                            author: string;
                            authorImageUrl: string;
                            work?: string;
                            /** @enum {string} */
                            language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                            isGenerated: boolean;
                            quote: string;
                        }[];
                        culturalGuide: {
                            timeline: {
                                date: string;
                                text: string;
                            }[];
                            forecast2030?: string;
                            notes: string[];
                        };
                        relations: {
                            synonyms: {
                                term: string;
                                note?: string;
                            }[];
                            antonyms: {
                                term: string;
                                note?: string;
                            }[];
                            family: string[];
                        };
                        translations: {
                            /** @enum {string} */
                            language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                            term: string;
                        }[];
                        visuals: {
                            hero: {
                                /** @enum {string} */
                                kind: "hero" | "infographic" | "meme";
                                imageKey: string;
                                prompt: string;
                                caption?: string;
                                concept: string;
                                width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                            };
                            infographic: {
                                /** @enum {string} */
                                kind: "hero" | "infographic" | "meme";
                                imageKey: string;
                                prompt: string;
                                caption?: string;
                                concept: string;
                                width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                            };
                            memes: {
                                /** @enum {string} */
                                kind: "hero" | "infographic" | "meme";
                                imageKey: string;
                                prompt: string;
                                caption?: string;
                                concept: string;
                                width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                            }[];
                        };
                        sources: {
                            index: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                            /** @enum {string} */
                            type: "wiktionary" | "wikipedia" | "dictionary" | "primary" | "scholarly";
                            title: string;
                            url?: string;
                            retrievedAt?: string;
                            year?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                            note?: string;
                        }[];
                        sourceVersions: {
                            model: string;
                            promptHash: string;
                            pipeline?: string;
                            stageModels?: {
                                [key: string]: string;
                            };
                        };
                        frequency: {
                            /** @enum {string} */
                            band: "rare" | "uncommon" | "common" | "frequent";
                            trendNote?: string;
                            series: {
                                year: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                value: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                            }[];
                            changeNote?: string;
                        } | null;
                        createdAt: string;
                        updatedAt: string;
                    } | null;
                };
            };
            /** @description WordNotReadyError */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordNotReadyError"];
                };
            };
        };
    };
    "words.getWordState": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                word: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": ({
                        /** @enum {string} */
                        status: "succeeded";
                        word: {
                            id: string & unknown;
                            word: string & unknown;
                            /** @enum {string} */
                            language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                            /** @enum {string} */
                            status: "pending" | "running" | "succeeded" | "failed";
                            coreDefinition: string;
                            lexical: {
                                partOfSpeech: string;
                                countable?: boolean;
                                plural?: {
                                    primary: string;
                                    also: string[];
                                };
                                register: string[];
                            };
                            pronunciation: {
                                ipa: string;
                                respelling: string;
                                audio: {
                                    uk: string | null;
                                    us: string | null;
                                };
                            };
                            tiers: {
                                quick: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                                everyday: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                                deep: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                                cultural: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                            };
                            etymology: {
                                summary: string;
                                firstAttested: {
                                    year: ((number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN")) | null;
                                    language: string;
                                };
                                origin: {
                                    from: string;
                                    to: string;
                                    gloss: string;
                                };
                                descent: {
                                    when: string;
                                    form: string;
                                    languageName: string;
                                    gloss: string;
                                    citation?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                }[];
                            };
                            authorExamples: {
                                author: string;
                                authorImageUrl: string;
                                work?: string;
                                /** @enum {string} */
                                language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                                isGenerated: boolean;
                                quote: string;
                            }[];
                            culturalGuide: {
                                timeline: {
                                    date: string;
                                    text: string;
                                }[];
                                forecast2030?: string;
                                notes: string[];
                            };
                            relations: {
                                synonyms: {
                                    term: string;
                                    note?: string;
                                }[];
                                antonyms: {
                                    term: string;
                                    note?: string;
                                }[];
                                family: string[];
                            };
                            translations: {
                                /** @enum {string} */
                                language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                                term: string;
                            }[];
                            visuals: {
                                hero: {
                                    /** @enum {string} */
                                    kind: "hero" | "infographic" | "meme";
                                    imageKey: string;
                                    prompt: string;
                                    caption?: string;
                                    concept: string;
                                    width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                };
                                infographic: {
                                    /** @enum {string} */
                                    kind: "hero" | "infographic" | "meme";
                                    imageKey: string;
                                    prompt: string;
                                    caption?: string;
                                    concept: string;
                                    width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                };
                                memes: {
                                    /** @enum {string} */
                                    kind: "hero" | "infographic" | "meme";
                                    imageKey: string;
                                    prompt: string;
                                    caption?: string;
                                    concept: string;
                                    width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                }[];
                            };
                            sources: {
                                index: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                /** @enum {string} */
                                type: "wiktionary" | "wikipedia" | "dictionary" | "primary" | "scholarly";
                                title: string;
                                url?: string;
                                retrievedAt?: string;
                                year?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                note?: string;
                            }[];
                            sourceVersions: {
                                model: string;
                                promptHash: string;
                                pipeline?: string;
                                stageModels?: {
                                    [key: string]: string;
                                };
                            };
                            frequency: {
                                /** @enum {string} */
                                band: "rare" | "uncommon" | "common" | "frequent";
                                trendNote?: string;
                                series: {
                                    year: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    value: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                }[];
                                changeNote?: string;
                            } | null;
                            createdAt: string;
                            updatedAt: string;
                        };
                    } | {
                        /** @enum {string} */
                        status: "pending" | "running" | "failed";
                        stages: {
                            /** @enum {string} */
                            stage: "fetch_source" | "enrich_etymology" | "enrich_tiers" | "enrich_authors" | "enrich_visuals" | "final_review";
                            /** @enum {string} */
                            status: "pending" | "running" | "succeeded" | "failed";
                            error?: {
                                message: string;
                                /** @enum {string} */
                                type: "not_found" | "timed_out" | "failed";
                            };
                        }[];
                    }) | null;
                };
            };
        };
    };
    "words.buildWord": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                word: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "succeeded";
                        word: {
                            id: string & unknown;
                            word: string & unknown;
                            /** @enum {string} */
                            language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                            /** @enum {string} */
                            status: "pending" | "running" | "succeeded" | "failed";
                            coreDefinition: string;
                            lexical: {
                                partOfSpeech: string;
                                countable?: boolean;
                                plural?: {
                                    primary: string;
                                    also: string[];
                                };
                                register: string[];
                            };
                            pronunciation: {
                                ipa: string;
                                respelling: string;
                                audio: {
                                    uk: string | null;
                                    us: string | null;
                                };
                            };
                            tiers: {
                                quick: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                                everyday: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                                deep: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                                cultural: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                            };
                            etymology: {
                                summary: string;
                                firstAttested: {
                                    year: ((number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN")) | null;
                                    language: string;
                                };
                                origin: {
                                    from: string;
                                    to: string;
                                    gloss: string;
                                };
                                descent: {
                                    when: string;
                                    form: string;
                                    languageName: string;
                                    gloss: string;
                                    citation?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                }[];
                            };
                            authorExamples: {
                                author: string;
                                authorImageUrl: string;
                                work?: string;
                                /** @enum {string} */
                                language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                                isGenerated: boolean;
                                quote: string;
                            }[];
                            culturalGuide: {
                                timeline: {
                                    date: string;
                                    text: string;
                                }[];
                                forecast2030?: string;
                                notes: string[];
                            };
                            relations: {
                                synonyms: {
                                    term: string;
                                    note?: string;
                                }[];
                                antonyms: {
                                    term: string;
                                    note?: string;
                                }[];
                                family: string[];
                            };
                            translations: {
                                /** @enum {string} */
                                language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                                term: string;
                            }[];
                            visuals: {
                                hero: {
                                    /** @enum {string} */
                                    kind: "hero" | "infographic" | "meme";
                                    imageKey: string;
                                    prompt: string;
                                    caption?: string;
                                    concept: string;
                                    width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                };
                                infographic: {
                                    /** @enum {string} */
                                    kind: "hero" | "infographic" | "meme";
                                    imageKey: string;
                                    prompt: string;
                                    caption?: string;
                                    concept: string;
                                    width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                };
                                memes: {
                                    /** @enum {string} */
                                    kind: "hero" | "infographic" | "meme";
                                    imageKey: string;
                                    prompt: string;
                                    caption?: string;
                                    concept: string;
                                    width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                }[];
                            };
                            sources: {
                                index: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                /** @enum {string} */
                                type: "wiktionary" | "wikipedia" | "dictionary" | "primary" | "scholarly";
                                title: string;
                                url?: string;
                                retrievedAt?: string;
                                year?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                note?: string;
                            }[];
                            sourceVersions: {
                                model: string;
                                promptHash: string;
                                pipeline?: string;
                                stageModels?: {
                                    [key: string]: string;
                                };
                            };
                            frequency: {
                                /** @enum {string} */
                                band: "rare" | "uncommon" | "common" | "frequent";
                                trendNote?: string;
                                series: {
                                    year: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    value: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                }[];
                                changeNote?: string;
                            } | null;
                            createdAt: string;
                            updatedAt: string;
                        };
                    } | {
                        /** @enum {string} */
                        status: "pending" | "running" | "failed";
                        stages: {
                            /** @enum {string} */
                            stage: "fetch_source" | "enrich_etymology" | "enrich_tiers" | "enrich_authors" | "enrich_visuals" | "final_review";
                            /** @enum {string} */
                            status: "pending" | "running" | "succeeded" | "failed";
                            error?: {
                                message: string;
                                /** @enum {string} */
                                type: "not_found" | "timed_out" | "failed";
                            };
                        }[];
                    };
                };
            };
            /** @description WordAlreadyReadyError | WordBuildInProgressError */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordAlreadyReadyError"] | components["schemas"]["WordBuildInProgressError"];
                };
            };
            /** @description InvalidWordInputError */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidWordInputError"];
                };
            };
        };
    };
    "words.search": {
        parameters: {
            query: {
                q?: string;
                status?: "pending" | "running" | "succeeded" | "failed";
                page: string & unknown;
                limit: string & unknown;
            };
            header?: never;
            path: {
                language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: ({
                            id: string & unknown;
                            word: string & unknown;
                            /** @enum {string} */
                            language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                            coreDefinition: string;
                            lexical: {
                                partOfSpeech: string;
                                countable?: boolean;
                                plural?: {
                                    primary: string;
                                    also: string[];
                                };
                                register: string[];
                            };
                            pronunciation: {
                                ipa: string;
                                respelling: string;
                                audio: {
                                    uk: string | null;
                                    us: string | null;
                                };
                            };
                            tiers: {
                                quick: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                                everyday: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                                deep: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                                cultural: {
                                    title: string;
                                    body: string;
                                    examples: {
                                        text: string;
                                        register: string;
                                    }[];
                                };
                            };
                            etymology: {
                                summary: string;
                                firstAttested: {
                                    year: ((number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN")) | null;
                                    language: string;
                                };
                                origin: {
                                    from: string;
                                    to: string;
                                    gloss: string;
                                };
                                descent: {
                                    when: string;
                                    form: string;
                                    languageName: string;
                                    gloss: string;
                                    citation?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                }[];
                            };
                            authorExamples: {
                                author: string;
                                authorImageUrl: string;
                                work?: string;
                                /** @enum {string} */
                                language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                                isGenerated: boolean;
                                quote: string;
                            }[];
                            culturalGuide: {
                                timeline: {
                                    date: string;
                                    text: string;
                                }[];
                                forecast2030?: string;
                                notes: string[];
                            };
                            relations: {
                                synonyms: {
                                    term: string;
                                    note?: string;
                                }[];
                                antonyms: {
                                    term: string;
                                    note?: string;
                                }[];
                                family: string[];
                            };
                            translations: {
                                /** @enum {string} */
                                language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                                term: string;
                            }[];
                            visuals: {
                                hero: {
                                    /** @enum {string} */
                                    kind: "hero" | "infographic" | "meme";
                                    imageKey: string;
                                    prompt: string;
                                    caption?: string;
                                    concept: string;
                                    width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                };
                                infographic: {
                                    /** @enum {string} */
                                    kind: "hero" | "infographic" | "meme";
                                    imageKey: string;
                                    prompt: string;
                                    caption?: string;
                                    concept: string;
                                    width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                };
                                memes: {
                                    /** @enum {string} */
                                    kind: "hero" | "infographic" | "meme";
                                    imageKey: string;
                                    prompt: string;
                                    caption?: string;
                                    concept: string;
                                    width?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    height?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                }[];
                            };
                            sources: {
                                index: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                /** @enum {string} */
                                type: "wiktionary" | "wikipedia" | "dictionary" | "primary" | "scholarly";
                                title: string;
                                url?: string;
                                retrievedAt?: string;
                                year?: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                note?: string;
                            }[];
                            sourceVersions: {
                                model: string;
                                promptHash: string;
                                pipeline?: string;
                                stageModels?: {
                                    [key: string]: string;
                                };
                            };
                            frequency: {
                                /** @enum {string} */
                                band: "rare" | "uncommon" | "common" | "frequent";
                                trendNote?: string;
                                series: {
                                    year: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                    value: (number | "NaN" | "Infinity" | "-Infinity") | ("Infinity" | "-Infinity" | "NaN");
                                }[];
                                changeNote?: string;
                            } | null;
                            createdAt: string;
                            updatedAt: string;
                            /** @enum {string} */
                            status: "succeeded";
                        } | {
                            id: string & unknown;
                            word: string & unknown;
                            /** @enum {string} */
                            language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
                            createdAt: string;
                            updatedAt: string;
                            /** @enum {string} */
                            status: "pending" | "running" | "failed";
                        })[];
                        pagination: {
                            page: number;
                            limit: number;
                            total: number;
                            pageCount: number;
                        };
                    };
                };
            };
        };
    };
    "words.counts": {
        parameters: {
            query?: {
                q?: string;
                status?: "pending" | "running" | "succeeded" | "failed";
            };
            header?: never;
            path: {
                language: "ru" | "en" | "es" | "fr" | "de" | "zh" | "ja" | "hi" | "ar" | "uk";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total: number & unknown;
                        pending: number & unknown;
                        running: number & unknown;
                        succeeded: number & unknown;
                        failed: number & unknown;
                    };
                };
            };
        };
    };
}
