#!/usr/bin/env bun
// gen:api — regenerate packages/fe-api-client/src/schema.gen.ts from the
// backend's LIVE OpenAPI document (F-PLAT-014 D4). There is no committed
// openapi.json crossing the repo boundary; the doc is fetched at gen time from
// a configurable base URL, so the drift gate needs a reachable backend.
//
//   KOTODAMA_API_URL=http://localhost:3000 bun run gen:api
//
// CI drift gate: run this, then fail on a dirty git diff of schema.gen.ts.
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const BASE = (process.env.KOTODAMA_API_URL ?? 'http://localhost:3000').replace(/\/+$/, '')
const DOC_URL = `${BASE}/api/openapi.json`
const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'packages',
  'fe-api-client',
  'src',
  'schema.gen.ts',
)

console.error(`gen:api → fetching ${DOC_URL}`)

let doc: unknown
try {
  const res = await fetch(DOC_URL)
  if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`)
  doc = await res.json()
} catch (err) {
  console.error(`\ngen:api FAILED to reach the OpenAPI endpoint at ${DOC_URL}.`)
  console.error('Point KOTODAMA_API_URL at a reachable backend (a local server or a staging URL).')
  console.error(String(err))
  process.exit(1)
}

// The banner is deliberately URL-FREE: baking the base URL in would make the
// committed file differ every time CI regenerates from a different host,
// falsely tripping the drift gate.
const banner =
  '// GENERATED by `bun run gen:api` from the backend OpenAPI document — DO NOT EDIT.\n' +
  '// Regenerate after any backend contract change; CI fails the drift gate on a dirty diff.\n\n'

const ast = await openapiTS(doc as Parameters<typeof openapiTS>[0])
await Bun.write(OUT, banner + astToString(ast))
console.error(`gen:api → wrote ${OUT}`)
